[package]
name = "humility-stack"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humility.workspace = true
humility-arch-arm.workspace = true
regex.workspace = true
