[package]
name = "humility-cmd-spctrl"
version = "0.1.0"
edition = "2021"
description = "RoT -> SP control"

[dependencies]
hif.workspace = true
clap.workspace = true
anyhow.workspace = true
parse_int.workspace = true

humility-cmd.workspace = true
humility-cli.workspace = true
humility-hiffy.workspace = true
