[package]
name = "humility-cmd-net"
version = "0.1.0"
edition = "2021"
description = "Management network device-side control and debugging"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
parse_int = { workspace = true }
colored = { workspace = true }

humility = { workspace = true }
humility-cmd = { workspace = true }
cmd-hiffy = { workspace = true }

hif = { workspace = true }
