[package]
name = "humility-cmd-openocd"
version = "0.1.0"
edition.workspace = true
description = "Run OpenOCD for the given archive"

[dependencies]
humility-cmd = { workspace = true }
humility-cli = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
