[package]
name = "humility-cmd-sbrmi10"
version = "0.1.0"
edition.workspace = true
description = "Sideband Remote Management Interface (SB-RMI v1.0) commands"

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
hif.workspace = true
parse_int.workspace = true
raw-cpuid.workspace = true
termimad.workspace = true
zerocopy.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-hiffy.workspace = true
humility-idol.workspace = true
