[package]
name = "humility-cmd-reset"
version = "0.1.0"
edition = "2021"
description = "Reset the chip using external pins"

[dependencies]
humility = { workspace = true }
humility-cmd = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
num-traits = { workspace = true }
log = { workspace = true }
