[package]
name = "humility-cmd-reset"
version = "0.1.0"
edition.workspace = true
description = "Reset the chip using external pins"

[dependencies]
humility = { workspace = true }
humility-cmd = { workspace = true }
humility-cli = { workspace = true }
humility-probes-core = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
