[package]
name = "humility-cmd-map"
version = "0.1.0"
edition = "2021"
description = "print memory map, with association of regions to tasks"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
clap = { version = "3.0.12", features = ["derive", "env"] }
anyhow = { version = "1.0.44", features = ["backtrace"] }
