[package]
name = "humility-cmd-map"
version = "0.1.0"
edition = "2021"
description = "print memory map, with association of regions to tasks"

[dependencies]
humility = { workspace = true }
humility-cmd = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
