[package]
name = "humility-cmd-ignition"
version = "0.1.0"
edition = "2021"
description = "Interact with the Igntion subsystem"

[dependencies]
anyhow = {version = "1.0.44", features = ["backtrace"] }
clap = {version = "3.0.12", features = ["derive", "env"] }
colored = "2.0"
log = {version = "0.4.8", features = ["std"]}
parse_int = "0.4.0"

drv-ignition-api = {git = "https://github.com/oxidecomputer/hubris", branch = "ignition", default-features = false}

humility = {path = "../../humility-core", package = "humility-core"}
humility-cmd = {path = "../../humility-cmd"}
humility-cmd-hiffy = {path = "../hiffy" }

hif = {git = "https://github.com/oxidecomputer/hif"}
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}
