[package]
name = "humility-cmd-gpio"
version = "0.1.0"
edition = "2021"
description = "GPIO pin manipulation"

[dependencies]
hif.workspace = true
clap.workspace = true
anyhow.workspace = true
parse_int.workspace = true

humility-cli.workspace = true
humility-cmd.workspace = true
humility-hiffy.workspace = true
