[package]
name = "humility-cmd-auxflash"
version = "0.1.0"
edition = "2021"
description = "manipulate auxiliary flash"

[dependencies]
anyhow = { version = "1.0.44", features = ["backtrace"] }
clap = { version = "3.0.12", features = ["derive", "env"] }
colored = "2.0.0"
indicatif = "0.15"
log = {version = "0.4.8", features = ["std"]}
parse_int = "0.4.0"

humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
humility-cmd-hiffy = { path = "../hiffy" }

hif = { git = "https://github.com/oxidecomputer/hif" }
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}
tlvc = {git = "https://github.com/oxidecomputer/tlvc"}
