[package]
name = "humility-cmd-hydrate"
version = "0.1.0"
edition = "2021"
description = "Rehydrate a bare memory dump"

[dependencies]
humility.workspace = true
humility-arch-arm.workspace = true
humility-cli.workspace = true
humility-cmd.workspace = true
humility-log.workspace = true

hubpack.workspace = true

anyhow.workspace = true
clap.workspace = true
colored.workspace = true
humpty.workspace = true
indexmap.workspace = true
parse_int.workspace = true
serde.workspace = true
serde_json.workspace = true
zerocopy.workspace = true
zip.workspace = true
