[package]
name = "humility-cmd-gdb"
version = "0.1.0"
edition = "2021"
description = "Attach to a running system using GDB"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
humility-cmd-openocd = { path = "../openocd" }
anyhow = { version = "1.0.44", features = ["backtrace"] }
clap = { version = "3.0.12", features = ["derive", "env"] }
ctrlc = "3.1.5"
tempfile = "3.3"
