[package]
name = "humility-cmd-gdb"
version = "0.1.0"
edition = "2021"
description = "Attach to a running system using GDB"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humility = { workspace = true }
humility-cmd = { workspace = true }
cmd-openocd = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
ctrlc = { workspace = true }
tempfile = { workspace = true }
