[package]
name = "humility-cmd-stmsecure"
version = "0.1.0"
edition.workspace = true
description = "change secure region settings on the stm32h7"

[dependencies]
clap.workspace = true
anyhow.workspace = true
parse_int.workspace = true

humility.workspace = true
humility-arch-arm.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
