// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Test data for STM32H7 GPIO configuration tests.
//! This file contains GPIO register block test data.

#![cfg(test)]

use super::stm32h7_parts::GpioRegisters;

pub struct TestData {
    pub group: char,
    pub addr: u32,
    pub config_data: &'static GpioRegisters,
    pub expected_outputs: [&'static str; 16],
}

pub const GPIO_TEST_DATA: &[TestData] = &[
    TestData {
        group: 'A',
        addr: 0x58020000,
        config_data: &GpioRegisters {
            moder: 0x6aabbffb,
            otyper: 0x00008000,
            ospeedr: 0x0c00c00c,
            pupdr: 0x24000000,
            idr: 0x0000c600,
            odr: 0x00008000,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0xb00000b0,
            afrh: 0x00077770,
        },
        expected_outputs: [
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF11:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF11:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF7:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF7:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF7:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF7:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:PullUp:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:LowSpeed:PullDown:AF0:Unlocked:InOne:OutZero",
            "Output:OutOpenDrain:LowSpeed:NoPull:AF0:Unlocked:InOne:OutOne",
        ],
    },
    TestData {
        group: 'B',
        addr: 0x58020400,
        config_data: &GpioRegisters {
            moder: 0x47fa90b7,
            otyper: 0x00000342,
            ospeedr: 0x2000cac0,
            pupdr: 0x00000000,
            idr: 0x000043f0,
            odr: 0x00000340,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0xc0000000,
            afrh: 0x55500044,
        },
        expected_outputs: [
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Output:OutOpenDrain:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Input:OutPushPull:HighSpeed:NoPull:AF0:Unlocked:InOne:OutZero",
            "Input:OutPushPull:HighSpeed:NoPull:AF0:Unlocked:InOne:OutZero",
            "Output:OutOpenDrain:LowSpeed:NoPull:AF0:Unlocked:InOne:OutOne",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutOpenDrain:LowSpeed:NoPull:AF4:Unlocked:InOne:OutOne",
            "Alternate:OutOpenDrain:LowSpeed:NoPull:AF4:Unlocked:InOne:OutOne",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Output:OutPushPull:LowSpeed:NoPull:AF5:Unlocked:InZero:OutZero",
            "Input:OutPushPull:HighSpeed:NoPull:AF5:Unlocked:InOne:OutZero",
            "Output:OutPushPull:LowSpeed:NoPull:AF5:Unlocked:InZero:OutZero",
        ],
    },
    TestData {
        group: 'C',
        addr: 0x58020800,
        config_data: &GpioRegisters {
            moder: 0xffffdadf,
            otyper: 0x00000000,
            ospeedr: 0x00002f00,
            pupdr: 0x00000000,
            idr: 0x00000004,
            odr: 0x00000004,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0x00bb0000,
            afrh: 0x00000000,
        },
        expected_outputs: [
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Output:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InOne:OutOne",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF11:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF11:Unlocked:InZero:OutZero",
            "Output:OutPushPull:HighSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
        ],
    },
    TestData {
        group: 'D',
        addr: 0x58020c00,
        config_data: &GpioRegisters {
            moder: 0xaaaaaaba,
            otyper: 0x00000000,
            ospeedr: 0xffffffcf,
            pupdr: 0x00001000,
            idr: 0x0000c7bb,
            odr: 0x00000000,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0xccccc0cc,
            afrh: 0xcccccccc,
        },
        expected_outputs: [
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:PullUp:AF12:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
        ],
    },
    TestData {
        group: 'E',
        addr: 0x58021000,
        config_data: &GpioRegisters {
            moder: 0xaaaaa9aa,
            otyper: 0x00000000,
            ospeedr: 0xffffc8cf,
            pupdr: 0x00000000,
            idr: 0x0000ffb0,
            odr: 0x00000010,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0xc550c5cc,
            afrh: 0xcccccccc,
        },
        expected_outputs: [
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF5:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InZero:OutZero",
            "Output:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InOne:OutOne",
            "Alternate:OutPushPull:HighSpeed:NoPull:AF5:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF5:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF12:Unlocked:InOne:OutZero",
        ],
    },
    TestData {
        group: 'F',
        addr: 0x58021400,
        config_data: &GpioRegisters {
            moder: 0xffeaafcf,
            otyper: 0x00000000,
            ospeedr: 0x00155020,
            pupdr: 0x00000010,
            idr: 0x00000044,
            odr: 0x00000000,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0x99000000,
            afrh: 0x000009aa,
        },
        expected_outputs: [
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Input:OutPushPull:HighSpeed:PullUp:AF0:Unlocked:InOne:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:MediumSpeed:NoPull:AF9:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:MediumSpeed:NoPull:AF9:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:MediumSpeed:NoPull:AF10:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:MediumSpeed:NoPull:AF10:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:MediumSpeed:NoPull:AF9:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
        ],
    },
    TestData {
        group: 'G',
        addr: 0x58021800,
        config_data: &GpioRegisters {
            moder: 0xfabfefff,
            otyper: 0x00000000,
            ospeedr: 0x0fc01000,
            pupdr: 0x00000000,
            idr: 0x00000040,
            odr: 0x00000000,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0x0a000000,
            afrh: 0x00bbb000,
        },
        expected_outputs: [
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:MediumSpeed:NoPull:AF10:Unlocked:InOne:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF11:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF11:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:VeryHighSpeed:NoPull:AF11:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
        ],
    },
    TestData {
        group: 'H',
        addr: 0x58021c00,
        config_data: &GpioRegisters {
            moder: 0xffffffff,
            otyper: 0x00000000,
            ospeedr: 0x00000000,
            pupdr: 0x00000000,
            idr: 0x00000000,
            odr: 0x00000000,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0x00000000,
            afrh: 0x00000000,
        },
        expected_outputs: [
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
        ],
    },
    TestData {
        group: 'I',
        addr: 0x58022000,
        config_data: &GpioRegisters {
            moder: 0x7fffffa9,
            otyper: 0x00000000,
            ospeedr: 0x00000020,
            pupdr: 0x00000000,
            idr: 0x00008001,
            odr: 0x00008001,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0x00005550,
            afrh: 0x00000000,
        },
        expected_outputs: [
            "Output:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InOne:OutOne",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF5:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:HighSpeed:NoPull:AF5:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF5:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Output:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InOne:OutOne",
        ],
    },
    TestData {
        group: 'J',
        addr: 0x58022400,
        config_data: &GpioRegisters {
            moder: 0xfffaffff,
            otyper: 0x00000000,
            ospeedr: 0x00000000,
            pupdr: 0x00000000,
            idr: 0x00000300,
            odr: 0x00000000,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0x00000000,
            afrh: 0x00000088,
        },
        expected_outputs: [
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF8:Unlocked:InOne:OutZero",
            "Alternate:OutPushPull:LowSpeed:NoPull:AF8:Unlocked:InOne:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
        ],
    },
    TestData {
        group: 'K',
        addr: 0x58022800,
        config_data: &GpioRegisters {
            moder: 0xffffffff,
            otyper: 0x00000000,
            ospeedr: 0x00000000,
            pupdr: 0x00000000,
            idr: 0x00000000,
            odr: 0x00000000,
            bsrr: 0x00000000,
            lckr: 0x00000000,
            afrl: 0x00000000,
            afrh: 0x00000000,
        },
        expected_outputs: [
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
            "Analog:OutPushPull:LowSpeed:NoPull:AF0:Unlocked:InZero:OutZero",
        ],
    },
];
