[package]
name = "humility-cmd-hash"
version = "0.1.0"
edition = "2021"
description = "Access to the HASH block"

[dependencies]
humility = { workspace = true }
humility-cmd = { workspace = true }
hif = { workspace = true }
clap = { workspace = true }
sha2 = { workspace = true }
anyhow = { workspace = true }
parse_int = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true }
