[package]
name = "humility-cmd-hash"
version = "0.1.0"
edition = "2021"
description = "Access to the HASH block"

[dependencies]
hif.workspace = true
clap.workspace = true
sha2.workspace = true
anyhow.workspace = true
parse_int.workspace = true
indicatif.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
humility-hiffy.workspace = true
