[package]
name = "humility-cmd-doc"
version = "0.1.0"
edition = "2021"
description = "print command documentation"

[build-dependencies]
cargo_metadata = { workspace = true }
cargo-readme = { workspace = true }
anyhow = { workspace = true }

[dependencies]
humility-cmd = { workspace = true }
humility-cli = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
termimad = { workspace = true }
