[package]
name = "humility-cmd-renbb"
version = "0.1.0"
edition = "2021"

[dependencies]
humility = { path = "../../humility-core", package = "humility-core" }
humility-cmd = { path = "../../humility-cmd" }
hif = { git = "https://github.com/oxidecomputer/hif" }
pmbus = { git = "https://github.com/oxidecomputer/pmbus" }
structopt = "0.3"
anyhow = { version = "1.0.44", features = ["backtrace"] }
indicatif = "0.15"
log = {version = "0.4.8", features = ["std"]}
parse_int = "0.4.0"
