[package]
name = "humility-cmd-trace"
version = "0.1.0"
edition = "2021"
description = "trace Hubris operations"

[dependencies]
humility = { workspace = true }
humility-cortex = { workspace = true }
humility-cmd = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
