[package]
name = "humility-cmd-spd"
version = "0.1.0"
edition = "2021"
description = "scan for and read SPD devices"

[dependencies]
hif.workspace = true
spd.workspace = true
clap.workspace = true
anyhow.workspace = true
jep106.workspace = true
parse_int.workspace = true

humility-cli.workspace = true
humility-cmd.workspace = true
humility-hiffy.workspace = true
humility-i2c.workspace = true
humility-log.workspace = true
humility.workspace = true
