[package]
name = "humility-cmd-fpga"
version = "0.1.0"
edition = "2021"
description = "FPGA operations"

[dependencies]
anyhow.workspace = true
clap.workspace = true
hif.workspace = true
humility-cli.workspace = true
humility-cmd.workspace = true
humility-hiffy.workspace = true
humility-idol.workspace = true
humility.workspace = true
indicatif.workspace = true
parse_int.workspace = true
