[package]
name = "humility-cmd-readvar"
version = "0.1.0"
edition = "2021"
description = "read and display a specified Hubris variable"

[dependencies]
clap.workspace = true
anyhow.workspace = true

humility.workspace = true
humility-cmd.workspace = true
humility-cli.workspace = true
