[package]
name = "humility-arch-arm"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
capstone.workspace = true
num-traits.workspace = true
num-derive.workspace = true
